version: "3.9"

services:
  app:
    build:
      args:
        uid: 1000
        gid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-taxi-9
    container_name: laravel-taxi-9
    restart: unless-stopped
    volumes:
        - ./:/var/www/html
        - ./docker-config/nginx.conf:/etc/nginx/nginx.conf
        - ./docker-config/php.ini:/etc/php8/conf.d/custom.ini
    networks:
        - docker_main
    ports:
        - 8093:8080

  # npm:
  #   image: node:17-alpine
  #   container_name: npm-menu
  #   restart: unless-stopped
  #   working_dir: /var/www/html
  #   entrypoint: ["npm"]
  #   depends_on:
  #   - app
  #   volumes:
  #   - ./:/var/www/html


networks:
  docker_main:
    name: docker_main
